### ISSUE TITLE
Web Link Invalid

### ISSUE THREAD

**Issue by CharlieMoon37** [chaostoolkit/chaostoolkit-documentation#128]
The first link within the README.md file of the chaostoolkit documentation is invalid:
"Get to the `documentation` of the Chaos Toolkit"
Which directs to the following link: http://docs.chaostoolkit.org/

https://github.com/chaostoolkit/chaostoolkit-documentation/blob/master/README.md

Not entirely sure where it is supposed to be directing ...

**Comment by ciaranevans** [comment]
@CharlieMoon37 good catch 😅 

It likely just needs to go to https://chaostoolkit.org
