### ISSUE TITLE
"pip install ..." Warning Message

### ISSUE THREAD

**Issue by CharlieMoon37** [chaostoolkit/chaostoolkit-documentation#129]
When using commands:
- pip install -U -r requirements.txt (https://chaostoolkit.org/reference/tutorial/#install-the-application-dependencies)
- pip install -U chaostoolkit (https://chaostoolkit.org/reference/tutorial/#install-the-chaos-toolkit)

We receive the warning message:
- “DEPRECATION: Configuring installation scheme with distutils config files is
     deprecated and will no longer work in the near future. If you are using a 
     Homebrew or Linuxbrew Python, please see discussion at 
     https://github.com/Homebrew/homebrew-core/issues/76621”

**Comment by ciaranevans** [comment]
Closing this one, looked at the Homebrew issue and it's a ongoing discussion between them and the Python maintainers, nothing we can do on our side

**Comment by CharlieMoon37** [comment]
Okay, perfect.
There's another with a warning message if you wanna take a look:
https://github.com/chaostoolkit/chaostoolkit-documentation/issues/131
