### ISSUE TITLE
Error while trying to create GCP chaos

### ISSUE THREAD

**Issue by rohit131989** [chaostoolkit/chaostoolkit-documentation#161]
The following error appears for each chaos type under GCP chaos: (Node Stop / Node Reset)

**Normal   FinalizerInited  10s   initFinalizers  Finalizer has been inited
  Normal   Updated          10s   initFinalizers  Successfully update finalizer of resource
  Normal   Updated          10s   desiredphase    Successfully update desiredPhase of resource
  Warning  Failed           10s   records         Failed to apply chaos: invalid character '÷' looking for beginning of value**

The logs of the chaos controller show the error (fail to get the compute service) to be in the below method
 "/chaos-mesh/controllers/chaosimpl/gcpchaos/nodestop/impl.go"

I could not make out why the '÷' symbol is messing up since there is NO value in input parameters apart from alpha-numeric values with hyphen(-).

**Comment by Lawouach** [comment]
Hello,

Could you give me a bit more context please?


What experiment did you run? Can we see the json file?

**Comment by rohit131989** [comment]
{
    "namespace": "chaos-mesh-experiments",
    "name": "exp-gcpchaos-nodestop2",
    "kind": "GCPChaos",
    "uid": "db97ad15-830c-47d5-a5ae-ed8dc9105c7e",
    "created_at": "2023-08-14T11:49:30Z",
    "status": "finished",
    "kube_object": {
        "kind": "GCPChaos",
        "apiVersion": "chaos-mesh.org/v1alpha1",
        "metadata": {
            "namespace": "chaos-mesh-experiments",
            "name": "exp-gcpchaos-nodestop2"
        },
        "spec": {
            "action": "node-stop",
            "duration": "2m",
            "secretName": "sa-secret",
            "project": "proj-1",
            "zone": "asia-southeast1-a",
            "instance": "instance-id-1"
        }
    }
}

**Comment by Lawouach** [comment]
Hey @rohit131989, maybe I'm a bit confused but are you talking about chaos mesh UI and products? This is teh repository for Chaos Toolkit, are you using it?

**Comment by rohit131989** [comment]
I am working on Chaos-Mesh wherein I am trying to inject GCP chaos type Stop-Node and getting the above error. I am creating the chaos experiment from chaos mesh UI.

**Comment by Lawouach** [comment]
Great, that sounds awesome. But you are creating this issue on the wrong project. Please visit https://github.com/chaos-mesh/chaos-mesh

**Comment by rohit131989** [comment]
Oops !!
Thanks

**Comment by Lawouach** [comment]
No worries at all. Feel free to checkout [chaostoolkit][https://chaostoolkit.org/) someday. We love new users in our community!
