### ISSUE TITLE
While executing the in chaos toolkit command prompt  Script we found this issue Could not find Python module

### ISSUE THREAD

**Issue by saimaheshk** [chaostoolkit/chaostoolkit-documentation#163]
While executing the Script we found this issue "Could not find Python module" in the chaos toolkit command prompt
here is the below one's script
Please check why that error is comming
JSON SCRIPT
{

  "title": "Chaos Test: Test Python Module",

  "description": "Test a simple Python module",

  "steady-state-hypothesis": {

    "title": "Server is responsive",

    "probes": [

      {

        "type": "probe",

        "name": "check-server-response",

        "tolerance": "3s",

        "provider": {

          "type": "http",

          "url": "http://127.0.0.1:5000"

        }

      }

    ]

  },

  "method": [

    {

      "type": "action",

      "name": "test-module-action",

      "provider": {

        "type": "python",

        "path": ".",

        "module": "my_test_module",

        "func": "hello_world",

        "arguments": {}

      }

    },

    {

      "type": "action",

      "name": "test-module-action",

      "provider": {

        "type": "python",

        "path": ".",

        "module": "my_test_module",

        "func": "add_numbers",

        "arguments": {

          "a": 3,

          "b": 4

        }

      }

    }

  ]

}

**Comment by Lawouach** [comment]
Make sure that the `my_test_module` python module can be found in the `PYTHONPATH`.
