### ISSUE TITLE
While execution the below code we getting this error in command prompt "unknown provider type 'shell'"

### ISSUE THREAD

**Issue by saimaheshk** [chaostoolkit/chaostoolkit-documentation#164]
{
  "title": "Controlled CPU Spike Experiment",
  "description": "Injects a low-intensity CPU spike for 5 minutes",
  "hypothesis": {
    "type": "steady-state",
    "title": "System performance remains stable under low CPU load",
    "probes": [
      {
        "type": "action",
        "name": "cpu-usage",
        "provider": {
          "type": "shell",
          "arguments": "mpstat 1"
        }
      },
      {
        "type": "service",
        "name": "web-service",
        "provider": {
          "type": "http",
          "url": "http://127.0.0.1:5000/"
        }
      }
    ]
  },
  "method": [
    {
      "type": "action",
      "name": "cpu-spike",
      "provider": {
        "type": "action",
        "path": "stress",
        "arguments": "-c 2"
      },
      "duration": 300
    }
  ] ,
  "steady-state-hypothesis": {
    "type": "steady-state",
    "title": "System performance recovers after CPU spike",
    "probes": [
      {
        "type": "action",
        "name": "cpu-usage",
        "provider": {
          "type": "shell",
          "arguments": "mpstat 1"
        }
      },
      {
        "type": "service",
        "name": "web-service",
        "provider": {
          "type": "http",
          "url": "http://127.0.0.1:5000/"
        }
      }
    ]
  }
}

**Comment by Lawouach** [comment]
Hello,

There is no `shell` provider. In your case, it would be `process` instead.

If you've seen `shell` in the documentation, it's a mistake indeed.
