### ISSUE TITLE
Document how to add time constraints to an experiment

### ISSUE THREAD

**Issue by dastergon** [chaostoolkit/chaostoolkit-documentation#25]
It is common, to run an experiment for a certain period of time and not indefinitely. In addition, sometimes, the operator may not be on the keyboard to stop the fault injection. Therefore, a timer or time controls would be useful when running an experiment. It would be very helpful to include a section mentioning all the available options.

**Comment by russmiles** [comment]
This issue has been closed here as it has been migrated to a feature discussion on the Chaos Toolkit lib project: https://github.com/chaostoolkit/chaostoolkit-lib/issues/39
