### ISSUE TITLE
"Get the code" in the tutorial should be more obviously mandatory

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit-documentation#32]

**Comment by Lawouach** [comment]
True enough. I think the code should be cloned from a git repo without pulling the entire doc repo. Maybe I could create a chaostoolkit-documentation-code repo and use it as a submodule of the main chaostoolkit-documentation repo.

**Comment by russmiles** [comment]
`chaostoolkit-documentation-support-code` ?

**Comment by Lawouach** [comment]
I thought chaostoolkit-documentation-code was already a mouthful... :D

**Comment by russmiles** [comment]
Also it's quite the jaunt to find the directory with the coding snippets for the tutorial. Something either friendlier, or more obvious from the tutorial, would be good

**Comment by Lawouach** [comment]
Yeah, the idea is that, with that new repo, things live at a top-level and you just clone and find everything more directly.

**Comment by Lawouach** [comment]
I have pushed the code to the new repo https://github.com/chaostoolkit/chaostoolkit-documentation-code

I'm going to use this module as a submodule of the docs (mostly so the docs can display code snippets directly).

**Comment by Lawouach** [comment]
done :)
