### ISSUE TITLE
Inconsistency between experiment example and the documentation.

### ISSUE THREAD

**Issue by sky4access** [chaostoolkit/chaostoolkit-documentation#59]
The example for 'Minimal Experiment' is not consistent with what documentation says. In the document, 'type' for the PROBE must be 'probe', and 'type' for the PROVIDER must be 'python', 'http', or 'process', but in the example, 'type' for the PROBE is 'python', and PROVIDER is missing the 'type'.  Here's that example. [https://docs.chaostoolkit.org/reference/api/experiment/#minimal-experiment](url)

**Comment by Lawouach** [comment]
Hey @sky4access, I haven't forgotten about this one but just didn't get the chance yet. sorry :/

**Comment by brencahill** [comment]
Also
`            "provider": {
                "module": "os.path",
                "func": "remove",`

I think module should be "os" rather than "os.path"
