### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by whostolebenfrog** [chaostoolkit/chaostoolkit-documentation#6]
Hey. Just spying on you both ;-) and noticed a typo.

`The chaostoolkit-documehtation is the`

On this page: "http://chaostoolkit.org/technology/"

**Comment by Lawouach** [comment]
Hah!

Thanks mate! I blame @russmiles and his non-native English of course :)

**Comment by russmiles** [comment]
Merci Ben!

**Comment by Lawouach** [comment]
That was fixed at some point :)
