### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gtfisher** [chaostoolkit/chaostoolkit-documentation#61]
Theres a broken link on the documentation index page

https://github.com/chaostoolkit/chaostoolkit-documentation/blob/master/sources/index.md

**Comment by russmiles** [comment]
This seems to be a missing image that was in static before.

**Comment by dmartin35** [comment]
detect-weakness.fbbaf411.svg cannot be found. 

Is the image gone ? or has the hash suffix changed ?

**Comment by russmiles** [comment]
Yep, https://chaostoolkit.org/static/detect-weakness.fbbaf411.svg is not being found.
