### ISSUE TITLE
missing action: create_service_endpoint

### ISSUE THREAD

**Issue by tdevilleduc** [chaostoolkit/chaostoolkit-documentation#76]
Why can i remove a service endpoint but i cannot create one ?
Maybe i miss something in the documentation

I'm running an experimentation where i have a springboot microservice and a mysql statefulset
I want to remove mysql service endpoint and check about my microservice resilience
But at the end of the experiment I dont have mysql service endpoint and i need to recreate it manually

Is there a way to recreate it with chaostoolkit ? # #

**Comment by dmartin35** [comment]
if you are talking about the chaos toolkit-kubernetes extension, there is no such function as creating a service endpoint. This is not missing from the documentation as it does not exist.

I would suggest to raise an issue to the extension repository for the missing function or even better submit a PR: https://github.com/chaostoolkit/chaostoolkit-kubernetes

**Comment by tdevilleduc** [comment]
https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/68
